In [33]:
%pip install pandas numpy

Note: you may need to restart the kernel to use updated packages.


In [34]:
import numpy as np
import pandas as pd

## Question 1
### Pandas version
What's the version of Pandas that you installed?

You can get the version information using the `__version__ `field:

In [35]:
pd.__version__

'2.2.3'

In [36]:
url = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv'

df = pd.read_csv(url)

In [37]:
df.sample(10)

Laptop       Status   Brand  \
1988  Lenovo V14 G2 ALC AMD Ryzen 5 5500U/8GB/256GB ...  Refurbished  Lenovo   
1288  Acer Extensa 15 EX215-22-R7D2 AMD Ryzen 3 3250...          New    Acer   
2061  MSI Katana GF66 12UE-091XES Intel Core i7-1270...  Refurbished     MSI   
1076  ASUS ROG Strix G17  G713PV-R97B46CB1 AMD Ryzen...          New    Asus   
1436  HP EliteBook 650 G9 Intel Core i5-1235U/8GB/51...          New      HP   
585   MSI Raider GE78HX 13VG-040ES Intel Core i7-137...          New     MSI   
783   MSI Pulse 17 B13VGK-435PT Intel Core i7-13700H...          New     MSI   
1749  Apple MacBook Pro Apple M1/16GB/1TB SSD/13.3" ...  Refurbished   Apple   
223   HP OMEN 17-cm2006ns Intel Core i7-13700HX/32GB...          New      HP   
1894  HP EliteBook x360 1030 G4 Intel Core i5-8265U/...  Refurbished      HP   

            Model            CPU  RAM  Storage Storage type       GPU  Screen  \
1988          V14    AMD Ryzen 5    8      256          SSD       NaN    14.0   
1288      Extensa    AMD Ryzen 3    8      256          SSD       NaN    15.6   
2061       Katana  Intel Core i7   16      512          SSD  RTX 3060    15.6   
1076          ROG    AMD Ryzen 9   16     1000          SSD  RTX 4060    17.3   
1436    EliteBook  Intel Core i5    8      512          SSD       NaN    15.6   
585        Raider  Intel Core i7   32     1000          SSD  RTX 4070    17.0   
783         Pulse  Intel Core i7   16     1000          SSD  RTX 4070    17.3   
1749  MacBook Pro       Apple M1   16     1000          SSD       NaN    13.3   
223          Omen  Intel Core i7   32     1000          SSD  RTX 4070    17.3   
1894    EliteBook  Intel Core i5    8      256          SSD       NaN    13.3   

     Touch  Final Price  
1988    No       739.61  
1288    No       479.00  
2061    No      1499.00  
1076    No      2203.07  
1436    No      1064.59  
585     No      2999.00  
783     No      2303.10  
1749    No      1999.00  
223     No      1999.00  
1894   Yes       866.00

## Question 2. Records count
How many records are in the dataset?

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Laptop        2160 non-null   object 
 1   Status        2160 non-null   object 
 2   Brand         2160 non-null   object 
 3   Model         2160 non-null   object 
 4   CPU           2160 non-null   object 
 5   RAM           2160 non-null   int64  
 6   Storage       2160 non-null   int64  
 7   Storage type  2118 non-null   object 
 8   GPU           789 non-null    object 
 9   Screen        2156 non-null   float64
 10  Touch         2160 non-null   object 
 11  Final Price   2160 non-null   float64
dtypes: float64(2), int64(2), object(8)
memory usage: 202.6+ KB


## Q3. Laptop brands
How many laptop brands are presented in the dataset?

In [39]:
distinct_laptop_brands = df.Brand.value_counts()
distinct_laptop_brands

Brand
Asus                415
HP                  368
Lenovo              366
MSI                 308
Acer                137
Apple               116
Dell                 84
Microsoft            77
Gigabyte             48
Razer                37
Medion               32
LG                   32
Alurin               29
PcCom                24
Samsung              22
Dynabook Toshiba     19
Vant                 11
Deep Gaming           8
Primux                8
Innjoo                6
Thomson               4
Prixton               3
Millenium             2
Denver                1
Jetwing               1
Realme                1
Toshiba               1
Name: count, dtype: int64

In [40]:
len(distinct_laptop_brands)

27

## Q4. Missing values
How many columns in the dataset have missing values?

In [41]:
cols_with_null_values = df.columns[df.isnull().any()].tolist()

In [42]:
len(cols_with_null_values)

3

## Q5. Maximum final price
What's the maximum final price of Dell notebooks in the dataset?

In [43]:
df.loc[df['Brand'] == 'Dell','Final Price'].max()

np.float64(3936.0)

## Q6. Median value of Screen
1. Find the median value of Screen column in the dataset.
2. Next, calculate the most frequent value of the same Screen column.
3. Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.

Now, calculate the median value of Screen once again.
Has it changed?

Hint: refer to existing mode and median functions to complete the task.

- Yes
- No

In [44]:
df.Screen.median()

np.float64(15.6)

In [45]:
df.Screen.mode()

0    15.6
Name: Screen, dtype: float64

In [46]:
df.Screen.fillna(df.Screen.mode(),inplace=True)

/tmp/ipykernel_26670/2701294211.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Screen.fillna(df.Screen.mode(),inplace=True)


In [47]:
df.Screen.median()

np.float64(15.6)

In [48]:
# I see no change

## Q7. Sum of weights
1. Select all the "Innjoo" laptops from the dataset.
2. Select only columns RAM, Storage, Screen.
3. Get the underlying NumPy array. Let's call it X.
4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
5. Compute the inverse of XTX.
6. Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

What's the sum of all the elements of the result?

In [49]:
df_injoo = df.loc[df['Brand'] == 'Innjoo']

In [51]:
df_injoo = df_injoo[['RAM','Storage','Screen']]

In [54]:
X = np.array(df_injoo)
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [59]:
x_transpose = X.T

XTX = x_transpose.dot(X)

XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [60]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [61]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [64]:
v = np.dot(XTX_inv.dot(x_transpose),y)
v.sum()

np.float64(91.2998806299555)